-- Seed Reference Data for Ledger System
-- This script populates account types and currencies

-- Account Types
INSERT INTO account_types (id, code, name, normal_balance)
VALUES (1, 'ASSET', 'Asset', 'DEBIT'),
       (2, 'LIABILITY', 'Liability', 'CREDIT'),
       (3, 'EQUITY', 'Equity', 'CREDIT'),
       (4, 'REVENUE', 'Revenue', 'CREDIT'),
       (5, 'EXPENSE', 'Expense', 'DEBIT'),
       (6, 'CONTRA_ASSET', 'Contra Asset', 'CREDIT'),
       (7, 'CONTRA_LIABILITY', 'Contra Liability', 'DEBIT')
ON CONFLICT (code) DO NOTHING;

-- Currencies
INSERT INTO currencies (code, name, symbol, precision)
VALUES ('USD', 'US Dollar', '$', 2),
       ('EUR', 'Euro', '€', 2),
       ('GBP', 'British Pound', '£', 2),
       ('JPY', 'Japanese Yen', '¥', 0),
       ('CNY', 'Chinese Yuan', '¥', 2),
       ('CAD', 'Canadian Dollar', '$', 2),
       ('AUD', 'Australian Dollar', '$', 2),
       ('CHF', 'Swiss Franc', 'Fr', 2),
       ('INR', 'Indian Rupee', '₹', 2),
       ('BRL', 'Brazilian Real', 'R$', 2),
       ('RUB', 'Russian Ruble', '₽', 2),
       ('KRW', 'South Korean Won', '₩', 0),
       ('MXN', 'Mexican Peso', '$', 2),
       ('ZAR', 'South African Rand', 'R', 2),
       ('SGD', 'Singapore Dollar', '$', 2),
       ('HKD', 'Hong Kong Dollar', '$', 2),
       ('SEK', 'Swedish Krona', 'kr', 2),
       ('NOK', 'Norwegian Krone', 'kr', 2),
       ('DKK', 'Danish Krone', 'kr', 2),
       ('PLN', 'Polish Złoty', 'zł', 2),
       ('TRY', 'Turkish Lira', '₺', 2),
       ('THB', 'Thai Baht', '฿', 2),
       ('IDR', 'Indonesian Rupiah', 'Rp', 0),
       ('MYR', 'Malaysian Ringgit', 'RM', 2),
       ('PHP', 'Philippine Peso', '₱', 2),
       ('AED', 'UAE Dirham', 'د.إ', 2),
       ('SAR', 'Saudi Riyal', '﷼', 2),
       ('ILS', 'Israeli Shekel', '₪', 2),
       ('CLP', 'Chilean Peso', '$', 0),
       ('COP', 'Colombian Peso', '$', 0),
       ('ARS', 'Argentine Peso', '$', 2),
       ('VND', 'Vietnamese Dong', '₫', 0),
       ('NZD', 'New Zealand Dollar', '$', 2),
       ('TWD', 'Taiwan Dollar', 'NT$', 2),
       ('CZK', 'Czech Koruna', 'Kč', 2),
       ('HUF', 'Hungarian Forint', 'Ft', 0),
       ('BGN', 'Bulgarian Lev', 'лв', 2),
       ('RON', 'Romanian Leu', 'lei', 2),
       ('HRK', 'Croatian Kuna', 'kn', 2),
       ('EGP', 'Egyptian Pound', '£', 2),
       ('PKR', 'Pakistani Rupee', '₨', 2),
       ('BDT', 'Bangladeshi Taka', '৳', 2),
       ('LKR', 'Sri Lankan Rupee', '₨', 2),
       ('NPR', 'Nepalese Rupee', '₨', 2),
       ('KES', 'Kenyan Shilling', 'KSh', 2),
       ('NGN', 'Nigerian Naira', '₦', 2),
       ('GHS', 'Ghanaian Cedi', '₵', 2),
       ('MAD', 'Moroccan Dirham', 'د.م.', 2),
       ('DZD', 'Algerian Dinar', 'د.ج', 2),
       ('TND', 'Tunisian Dinar', 'د.ت', 3),
       ('IQD', 'Iraqi Dinar', 'ع.د', 3),
       ('KWD', 'Kuwaiti Dinar', 'د.ك', 3),
       ('BHD', 'Bahraini Dinar', 'د.ب', 3),
       ('OMR', 'Omani Rial', 'ر.ع.', 3),
       ('JOD', 'Jordanian Dinar', 'د.ا', 3),
       ('QAR', 'Qatari Riyal', 'ر.ق', 2),
       ('IRR', 'Iranian Rial', '﷼', 0),
       ('AFN', 'Afghan Afghani', '؋', 2),
       ('UZS', 'Uzbekistani Som', 'so''m', 0),
       ('KZT', 'Kazakhstani Tenge', '₸', 2),
       ('AMD', 'Armenian Dram', '֏', 0),
       ('GEL', 'Georgian Lari', '₾', 2),
       ('AZN', 'Azerbaijani Manat', '₼', 2),
       ('BYN', 'Belarusian Ruble', 'Br', 2),
       ('UAH', 'Ukrainian Hryvnia', '₴', 2),
       ('MDL', 'Moldovan Leu', 'L', 2),
       ('ALL', 'Albanian Lek', 'L', 2),
       ('MKD', 'Macedonian Denar', 'ден', 2),
       ('RSD', 'Serbian Dinar', 'дин', 2),
       ('BAM', 'Bosnia and Herzegovina Convertible Mark', 'KM', 2),
       ('ISK', 'Icelandic Króna', 'kr', 0)
ON CONFLICT (code) DO NOTHING;
